### ISSUE TITLE
kobayashi/kobayashi_demoをnomlab/masterにmergeする

### ISSUE THREAD

**Issue by ikeda-yuko** [nomlab/camome#21]
#19 の Task issue である．
kobayashi/kobayashi_demo を nomlab/master に merge する．

**Comment by kobayashi1027** [comment]
kobayashi/kobayashi_demo を nomlab/master に merge した．
ただし，最後のcommit(https://github.com/kobayashi1027/camome/commit/f83d1676b9e79ab82a732c1808fed3a9887a020e)は，デモ用の実装に寄りすぎていたため，merge しなかった．
