### ISSUE TITLE
Googleカレンダーの予定を直接camomeのfull-calendarに表示できるようにする

### ISSUE THREAD

**Issue by tsubokawa-t** [nomlab/camome#37]
Created from [AI0265](http://jay.swlab.cs.okayama-u.ac.jp/minutes/302?ai=0265) of minute 302.
      +  Googleカレンダーの予定を直接camomeのfull-calendarに表示できるようにする -->(乃村，坪川 !:0265)

**Comment by tsubokawa-t** [comment]
Google Calendar APIでGoogleカレンダーの予定を取得し，full-calendarに表示できるようにした．
以下の流れでfull-calendarに予定を表示する．

1. full-calendarのページを開いたとき，ajaxによりコントローラのメソッド(fetch)にGETリクエストを送信
2. 1のメソッドはGoogle Calendar APIにより取得したデータを返却
3. 2で返却されたデータから，それぞれの予定の件名と開始時間を取り出し，full-calendarのeventsに与える．

今後の課題
1.クライアント情報の設定方法
2.取得するGoogleカレンダーの予定の範囲の設定

**Comment by tsubokawa-t** [comment]
以下の変更を行った．

1.  FullCalendar に表示している日付の範囲のGoogleカレンダーの予定を取得
2.  認証情報を設定ファイルに記述

1 について具体的には以下のことを行った．
* FullCalendarのオプションである``events:``から直接``/events/fetch``にリクエストを送信
(このとき表示されているカレンダの開始日と終了日がパラメータとして送信される)
* ``/events/fetch``では送られてきたパラメータを使用し，Google API により予定を取得
* 取得した予定を FullCalendar に適した形にして返却

2 について具体的には以下のことを行った．
* ``application_id`` と ``application_secret`` を ``application_settings.yml`` に記述

今後の課題
* etagを使用し，予定の取得を効率化
* Googleアカウントの ID をログインしているユーザから取得

**Comment by tsubokawa-t** [comment]
## 現状報告

認証情報をファイルから読み込まずに認証を行えるように修正した．
pericanで行われているGoogleカレンダ認証を参考にした認証方法では以下の問題があった．

* `Google::Auth::Stores::FileTokenStore`により，認証情報の記述されたyaml形式のファイルを読み込む必要がある
* すべてのユーザの認証情報がサーバの同じ場所に保存される

そこで，ファイルを読み込まずに`Google::Auth::Stores::FileTokenStore`と同じ働きをする以下のようなクラスを作成した．

* クラスを`.new`する際，認証情報をハッシュで引数に与える
* `YAML::Store`ではなく，ハッシュにより認証情報の読み書きを行う

このクラスを用いた場合と，`Google::Auth::Stores::FileTokenStore`を用いた場合で同様の結果を得られることを確認した．

## 今後の課題

* DBに保存されている認証情報との連携
* アクセストークンがリフレッシュされることへの対応

**Comment by yoshida564** [comment]
#47 でFullCalendarに表示する機能を実装するため，本Issueはcloseする．
