### ISSUE TITLE
camomeにPOSTされた情報を受け取る機能をAccessTokenを用いて実装する

### ISSUE THREAD

**Issue by kobayashi1027** [nomlab/camome#38]
Created from [AI0263](http://jay.swlab.cs.okayama-u.ac.jp/minutes/302?ai=0263) of minute 302.
- camomeにPOSTされた情報を受け取る機能をbasic認証を用いて実装する． -->(市川，小林 !:0263)

**Comment by ichikawa85** [comment]
## やったこと

1. Userモデルに"api_token" columnを追加

2. app/controller/application_controller.rb
skip_before_action :verify_authenticity_token, if: -> {request.format.json?}を追加
リクエストがJSONだったら，CSRFを無効化

3. before_action :decision_token
tokenの有無で認証方法(token, devise)を分岐

4. authenticate_user_from_token
tokenで認証するメソッドを作成

## 使い方
(例)
``` bash
curl -v -H "Accept: application/json" -H "Content-type: application/json" -X POST \
 -d '{"uid": "1", "date": "2016-10-04 00:44:25", "summary": "test", "options":   \
{"description": "test", "originator": "fuga@fuga.com", "recipients": "hoge@hoge.com"},  \
"content_type": "Resource::Mail"}' "http://localhost:3000/clams?api_token=test"
```

**Comment by ichikawa85** [comment]
## 現状報告
以下の2点を行った．
1. token を用いた認証に成功した後に CSRF を無効化するようにした
2. tokenを生成するメソッドの追加した

## 今後の課題
2のメソッドをViewから呼ぶ部分の実装
