### ISSUE TITLE
Redisサーバの環境構築をdockerで行う

### ISSUE THREAD

**Issue by kanzawa2** [nomlab/camome#50]
Created from [AI0381](http://jay.swlab.cs.okayama-u.ac.jp/minutes/437?ai=0381) of minute 437.
+ Redisサーバの環境構築をdockerで行う．-->(乃村，神澤 !:0381)

**Comment by kanzawa2** [comment]
### 現状報告

実験的にnompal上にdockerを用いてredisサーバを立ち上げ，正常に起動していることを確認した．
dockerの設定に関してはまだ調査できていないため，今後調査する．

**Comment by kanzawa2** [comment]
以下のサイトを参考に，camomeとデータベースのコンテナをdocker composeを用いて立ち上げた．
https://docs.docker.com/compose/rails/

camomeで用いられているデータベースは，sqlite3だが，sqlite3のDockerfileが公式に配布されていないため，データベースのコンテナとして，postgresのコンテナを立ち上げた．

今後は，camomeに合わせてコンテナの設定を検討する．

**Comment by kjtbw** [comment]
この issue の内容は #54 に内包されているため，close する．
